# Generated by Django 4.2.29 on 2026-04-06 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.IntegerField()),
                ('unit_title', models.CharField(max_length=200)),
                ('topics', models.TextField(help_text='Enter topics separated by new lines')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_units', to='core.subject')),
            ],
            options={
                'ordering': ['unit_number'],
                'unique_together': {('subject', 'unit_number')},
            },
        ),
    ]
